name: Build

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [ "Release" ]
    types: [ completed ]

jobs:

  build:
    name: Build and create a release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      
      - name: Push Print
        if: github.event_name == 'push'
        run: |
          echo "PUSH"


      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Release Print
        if: github.event_name == 'workflow_run'
        run: |
          echo "Versione: ${{ steps.get_version.outputs.VERSION }}"
    
