name: Build

on:
  release:
    types: [ published ]

jobs:

  build:
    name: Build and create a release
    runs-on: ubuntu-latest
    steps: 
      
      - name: Print
        if: github.event_name == 'release'
        run: |
          echo "build versione ${{ github.event.release.tag_name }}"

    
