name: Build

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [ "Release" ]
    types: [ completed ]

jobs:

  build:
    name: Build and create a release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      
      - name: Push Print
        if: github.event_name == 'push'
        run: |
          echo "PUSH"

      - name: Release Tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"  
        if: github.event_name == 'workflow_run'
 
      - name: Release Print
        if: github.event_name == 'workflow_run'
        run: |
          echo "Versione ${{ steps.previoustag.outputs.tag }}"
