name: Build

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [ "Release" ]
    types: [ completed ]

jobs:

  build:
    name: Build and create a release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      
      - name: Push Print
        if: github.event_name == 'push'
        run: |
          echo "PUSH"

      - name: Release Print
        if: github.event_name == 'workflow_run'
        run: |
          echo "REF: ${{ GITHUB_REF }}"
          echo "Versione: ${GITHUB_REF/refs\/tags\//}"
          echo "Versione2: ${{GITHUB_REF/refs\/tags\//}}"
          echo "Versione3: ${GITHUB_REF##*/}"
          echo "Versione4: ${{GITHUB_REF##*/}}"

    
