name: Build

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [ "Release" ]
    types: [ completed ]

jobs:

  build:
    name: Build and create a release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      
      - uses: actions/checkout@v2
      
      - name: Push Print
        if: github.event_name == 'push'
        run: |
          echo "PUSH"

      - name: Release Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: github.event_name == 'workflow_run'
 
      - name: Release Print
        if: github.event_name == 'workflow_run'
        run: |
          echo "Versione ${{ steps.get-latest-tag.outputs.tag }}"
