name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      prerelease:
        description: 'Set TRUE for pre-release'
        required: false
        default: 'FALSE'

jobs:

  release:
    name: Publish a new release
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          release_name: "Versione ${{ github.event.inputs.version }}"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease == 'TRUE' }}
          
      - name: create changelog page
        run: |
          mkdir docs
          echo "---" > docs/release.md
          echo "layout: default" >> docs/release.md
          echo "---\n\n" >> docs/release.md
          echo "tag: v${{ github.event.inputs.version }}"  >> docs/release.md
          echo "release: Versione ${{ github.event.inputs.version }}"  >> docs/release.md
          echo "change-log: ${{ steps.changelog.outputs.changelog }}"  >> docs/release.md
          
      - name: Add and commit
        uses: EndBug/add-and-commit@v7
        with:
          add: docs/release.md --force
          branch: gh-pages
          branch_mode: create
          push: '--force --set-upstream origin gh-pages'
          pull: 'NO-PULL'
          default_author: github_actor
          message: 'Load page'
