name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      prerelease:
        description: 'Set TRUE for pre-release'
        required: false
        default: 'FALSE'

jobs:

  release:
    name: Publish a new release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    outputs:
      tag: ${{ steps.previous-release.outputs.release }}
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get latest release tag
        id: previous-release
        uses: rez0n/actions-github-release@main
        env:
          token: ${{ github.token }}
          repository: "iisgiua/giuaschool"
          type: "stable"

      - uses: ncipollo/release-action@v1
        with:
          body: 'prova...'
          draft: false
          prerelease: ${{ github.event.inputs.prerelease == 'TRUE' }}
          tag: "v${{ github.event.inputs.version }}"
          name: "Versione ${{ github.event.inputs.version }}"
        
          
