# This is a basic workflow to help you get started with Actions

name: test

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
      

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3
                
      - name: Debug
        run: |
         echo "-->  ${{ github.event_name }}"
         echo "-->  ${{ github.ref }}"
   
      - name: Test
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} 
        run: |
         echo ":::::::::OK DEPLOY"
        
