# This is a basic workflow to help you get started with Actions

name: test

on:
   workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
         
      - uses: cardinalby/git-get-release-action@v1
        id: latest-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true    
    
    
      - name: Get changed files using a comma separator
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          separator: " "
          base_sha: "${{ steps.latest-release.outputs.target_commitish }}"
          
      - name: List all added files
        run: |
         echo "${{ steps.latest-release.outputs.tag_name }}"
         echo "${{ steps.latest-release.outputs.url }}"
         echo "${{ steps.latest-release.outputs.target_commitish }}"
         echo "----"
         echo ${{ steps.changed-files.outputs.all_changed_files }}
         echo "----"
