# This is a basic workflow to help you get started with Actions

name: test

on:
   workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
         
      - name: Get latest release tag
        id: latest-release
        uses: jossef/action-latest-release-info@v1.2.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
            
      - name: Test
        run: |
         echo "${{ steps.latest-release.outputs.tag_name }}"
         echo "----"
         echo "Prova ${ ${{ steps.latest-release.outputs.tag_name }}:1 }"
  
