# This is a basic workflow to help you get started with Actions

name: test

on:
   workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Get changed files using a comma separator
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          separator: "\n"
          base_sha: b427822

      - name: List all added files
        run: |
         for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
         done
         echo "----"
         echo ${{ steps.changed-files.outputs.all_changed_files }}
